### ISSUE TITLE
Upřesnění popisů

### ISSUE THREAD

**Issue by vojkny** [opendatalabcz/ockovani-covid-pages#2]
Vážení,

předem chci zmínit, že Vaší aplikace si nesmírně cením a denně ji sleduji. Několika polím ze screenshotu níže ani po zevrubnějším studiu nerozumím a tak vyvozuji, že nemusím být jediný a rád bych poprosil o upřesnění.

<img width="1128" alt="Screenshot 2021-06-28 at 21 54 04" src="https://user-images.githubusercontent.com/401107/123695894-67cc5500-d85b-11eb-9b83-3ca3c898bd68.png">

1. "Rezervací denně – průměrný počet rezervací denně za posledních 7 dní"
Navrhuji úpravu: "Registrací denně – denní průměr registrací za posledních 7 dní"

2. "Dnešní kapacita 1./2. dávky" / "Dnešní celková kapacita"
Tomuhle termínu bohužel vůbec nerozumím ani z detailního popisu. Jaký je vztah k čekajícím? V číslu nevidím žádnou souvislost k tomu, co se za den proočkovalo – můžete prosím upřesnit? 

3. "Doba ve frontě"
Jedná se o frontu k registraci na termín, či čekání na očkování od registrace?

4. "7denní úspěšnost"
Taktéž nerozumím ani z detailního popisu. Co by číslo mělo symbolizovat? Znamená vyšší číslo něco lepšího?

Omlouvám se za svou možnou "tupost", třeba mi to budete moci ulehčit :-)

Díky a hezký den,

VK

**Comment by jan-stanek** [comment]
Dobrý den,
1. mezi registrací a rezervací je rozdíl, rezervace je až získání konkrétního termínu
2. toto jsou sloty (obsazené i neobsazené termíny) na dnešní den, které uvádějí očkovací místa, u 2. dávek se bohužel stalo to, že některé očkovací místo zadalo vysoké číslo, které neodpovídá realitě
3. průměrná doba od regsitrace, jak dlouho čekají ti, kdo ještě nemají vybraný termín
4. jaká část z lidí, kteří se zaregistrovali minulý za posledních 7 dní už si zvolila termín (čím vyšší číslo, tím lépe)

Jan Staněk

**Comment by vojkny** [comment]
Děkuji, takto to dává větší smysl – nechtěli byste podle toho tu textaci upravit/vylepšit?

**Comment by msusicky** [comment]
Aktualizace stranek byla zastavena a dlouho bez reakce
